@startuml

    enum TipoMovimentacao{
        - saida
        - entrada

    }

    enum Estalecimento{
        - Loja
        - Lanche

    }


    class Usuario{
        -id
        - nome

    }

    class Movimentacao{
        - dataMov
    }

    class Estoque{
        - nomeProduto
    }

    class Produto{
        - nome
        - valor
        - qtdProdutos
    }

    class Venda{
        - qtdTotal
        - qtdProdutos
    }

    ' Venda -- Movimentacao
    Usuario -- Venda
    Venda -- Produto
    Movimentacao -- Produto
    Movimentacao -- Estoque
    Estoque -- Produto
    Usuario -- Movimentacao

    TipoMovimentacao -- Movimentacao
    Estalecimento -- Movimentacao





    ' Produto "0..*" <-- "1" Venda

    ' Produto "0..*" <-- "1" Estoque


    ' Venda "1" <-- "1" Movimentacao









@enduml
